set(CMAKE_TARGET_SYSTEM_NAME Windows)
set(CMAKE_TARGET_SYSTEM_PROCESSOR AMD64)
message(STATUS "CMAKE_TARGET_SYSTEM_NAME: ${CMAKE_TARGET_SYSTEM_NAME}")
message(STATUS "CMAKE_TARGET_SYSTEM_PROCESSOR: ${CMAKE_TARGET_SYSTEM_PROCESSOR}")
