string(TOLOWER ${CMAKE_HOST_SYSTEM_NAME} CMAKE_TARGET_SYSTEM_NAME)
string(TOLOWER ${CMAKE_SYSTEM_PROCESSOR} CMAKE_TARGET_SYSTEM_PROCESSOR)

# windows : mingw32, mingw64, msvc
# linux : gcc, clang
# embedded : gcc
set(CMAKE_TARGET_TOOLCHAIN_NAME gcc)

message(STATUS "CMAKE_TARGET_SYSTEM_NAME: ${CMAKE_TARGET_SYSTEM_NAME}")
message(STATUS "CMAKE_TARGET_SYSTEM_PROCESSOR: ${CMAKE_TARGET_SYSTEM_PROCESSOR}")
message(STATUS "CMAKE_TARGET_TOOLCHAIN_NAME: ${CMAKE_TARGET_TOOLCHAIN_NAME}")